site_name: Test van Syps
site_url: https://readthedocs.org/projects/klantinteractie-servicesysteem/

nav:
  - Home: index.md
  - Intro: intro.md
  - Installatie: INSTALLATION.md
  
theme: readthedocs
